### PR TITLE
Included version check in ValidateGlb and added a spec

### PR DESCRIPTION
**Pull request by Rudraksha20**
@lilleyse 

Worked on issue #98. Included version check for Glb and added a spec for the same. Have not updated the code for the sensitive test case will resolve the merge conflicts manually and rebase.

### CODE REVIEW

**Comment by Rudraksha20** [comment]
@lilleyse In the validateB3dmSpec, is the entire bottom section of the code from `function createB3dm(options)` deleted?

**Comment by lilleyse** [comment]
That area was moved to spevUtility.js so that other files like validateCmptSpec could also create b3dms

**Comment by Rudraksha20** [comment]
@lilleyse for the function `createHeaderGlb()` do you want me to add that function to validateCmptSpec or keep it in the `validateB3dmSpec`?

**Comment by lilleyse** [comment]
That can also go in `createHeaderGlb` since it will be used by functions in `specUtility`.

**Comment by Rudraksha20** [comment]
@lilleyse ok I am closing this PR, rebasing the code and re-starting it.

**Pull request closed without merging**
