### PR TITLE
glTF 2.0 in samples generator

### PR DESCRIPTION
**Pull request by lilleyse**
Updated the samples generator project to use glTF 2.0.

The tilesets all load in Cesium and the embedded glTFs pass [glTF Validator](https://github.com/KhronosGroup/glTF-Validator).

Not quite ready for merging yet because
* [x] Some samples are commented out. This includes anything that used features from `gltf-pipeline#1.0` including texture compression, quantization, or oct encoding.
    * [x] Tree billboard tileset requires [KHR_techniques_webgl](https://github.com/KhronosGroup/glTF/issues/1217) to be ready
* [x] package.json uses gltf-pipeline 1.0.5 but requires gltf-pipeline 2.0.0 which isn't released yet.

After merge:
* [ ] Update [3d-tiles-samples](https://github.com/AnalyticalGraphicsInc/3d-tiles-samples) after [KHR_techniques_webgl in Cesium](https://github.com/AnalyticalGraphicsInc/cesium/pull/6805) is merged. The tree billboard sample requires that extension.

### CODE REVIEW

**Comment by lilleyse** [comment]
This is ready now.

Review the Cesium PR first - https://github.com/AnalyticalGraphicsInc/cesium/pull/6857. The review on this one isn't as urgent.

**Comment by ggetz** [comment]
PointCloudDraco and PointCloudDracoBatched are still using `url` instead of `uri`

**Comment by lilleyse** [comment]
> PointCloudDraco and PointCloudDracoBatched are still using url instead of uri

I'll make sure to fix that in https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/150

@ggetz would you mind doing a quick review?

**Comment by lilleyse** [comment]
> Running the script gives me an error in Node 6.

I tried 6.14.4 and didn't get that error. What version are you using?

> This no longer outputs Point Cloud Draco tiles at the same path, so related tests in Cesium are failing.

Those are part of https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/150

> Also tilesets of tilesets test is failing:

That is fixed in https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/pull/151

**Comment by ggetz** [comment]
> I tried 6.14.4 and didn't get that error. What version are you using?

Using 6.14.3

> Those are part of #150 
> That is fixed in #151

What's the plan there, did we want to get those merge in before?

**Comment by lilleyse** [comment]
#151 can be merged before, and then I can merge master into here.
#150 I still need to finish up but doesn't need to hold up this PR.

I switched to 6.14.3, cleared away `node_modules`, and didn't get any errors.

**Comment by ggetz** [comment]
Ok sounds good. Reviewed and merged #151.

And I also blew away node_modules, this fixed the error. Thanks!

**Comment by lilleyse** [comment]
Merged in master - should be ready to go now.

**Comment by ggetz** [comment]
:+1:

**Pull request merged**
