### PR TITLE
Clean up 3d-tiles-tools.js

### PR DESCRIPTION
**Pull request by lilleyse**
Just some cleanup in the 3d-tiles-tools.js file. The one breaking change is removing the `-z` option for `optimizeB3dm` to gzip the b3dm. Instead it will gzip automatically if the input file is gzipped.

### CODE REVIEW

**Comment by shehzan10** [comment]
Do you think it would make it useful to make `force` a part of `options` across all the function and make options as standard instead?

**Comment by shehzan10** [comment]
Closed by mistake.

**Comment by lilleyse** [comment]
> Do you think it would make it useful to make force a part of options across all the function and make options as standard instead?

I think since this is all in the bin script its ok for now. If we find ourselves adding more of the same options to every function we could go with that approach.

**Comment by shehzan10** [comment]
Just to confirm, if the input B3dm is unzipped and the user wanted it to be zipped, then the user would need to call both `optimizeB3dm` followed by `gzip`?

The code changes look solid.

**Comment by lilleyse** [comment]
> Just to confirm, if the input B3dm is unzipped and the user wanted it to be zipped, then the user would need to call both optimizeB3dm followed by gzip?

We don't actually have a command that gzips individual tiles, just tilesets. My main reason for removing the option is we don't give that option for any of the other tools, like `glbToB3dm` and others.

**Pull request merged**
