### PR TITLE
Generate cached tiles for expire tileset

### PR DESCRIPTION
**Pull request by lilleyse**
For https://github.com/AnalyticalGraphicsInc/3d-tiles-samples/pull/13

### CODE REVIEW

**Comment by lilleyse** [comment]
I have a few more changes to make + adding a new tileset, I'll bump when ready.

**Comment by lilleyse** [comment]
Updated.

@likangning93 do you want to review? Should be quick.

**Comment by lilleyse** [comment]
@likangning93 bump.

After this I want to do the project rename https://github.com/AnalyticalGraphicsInc/3d-tiles-tools/issues/60

**Comment by likangning93** [comment]
@lilleyse sorry for the (extremely slow) response! Changes look good to me. I guess has this been open long enough that it needs master merged in to pass Travis?

**Comment by lilleyse** [comment]
Travis is just broken on this repo right now, you can ignore the failure.

**Comment by likangning93** [comment]
Tests and eslint in `generator` pass locally for me, but in `tools` I get a failure for `1) optimizeGlb compresses textures in a glb using the gltf-pipeline` and a massive console output. Is that a known problem?

**Comment by likangning93** [comment]
I do get the same failure in master, though.

**Comment by lilleyse** [comment]
> Tests and eslint in generator pass locally for me, but in tools I get a failure for 1) optimizeGlb compresses textures in a glb using the gltf-pipeline and a massive console output. Is that a known problem?

Oh that might be new.. I'll look into that.

**Comment by lilleyse** [comment]
I don't get that error when run locally, but I know there's been trouble with running the etc compression tool on certain machines. I think this is safe to ignore here and fix https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/258 eventually.

**Comment by likangning93** [comment]
@lilleyse sorry it's been such a long time for this one... does this just have conflicts with `master` now?

**Comment by lilleyse** [comment]
Merged in master.

**Pull request merged**
